// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtz7LYbFl3BPw7TMBFHGbARL7d2P-hIkQ',
    appId: '1:828623567114:web:879d38af25b6d04ae6e2f3',
    messagingSenderId: '828623567114',
    projectId: 'notas-3c51d',
    authDomain: 'notas-3c51d.firebaseapp.com',
    storageBucket: 'notas-3c51d.appspot.com',
    measurementId: 'G-JGHR37LP10',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXd9atVZdQL0hDWYBvFCoFY7jMoGFgKks',
    appId: '1:828623567114:android:b6d1a7c54a86a23ae6e2f3',
    messagingSenderId: '828623567114',
    projectId: 'notas-3c51d',
    storageBucket: 'notas-3c51d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhWYN64lFCPF56Yl9I7I7CejAj4307ZhM',
    appId: '1:828623567114:ios:80f00557f23e1f5be6e2f3',
    messagingSenderId: '828623567114',
    projectId: 'notas-3c51d',
    storageBucket: 'notas-3c51d.appspot.com',
    iosClientId:
        '828623567114-5u1j71lmsun4c449riqvpq2of81g0c2s.apps.googleusercontent.com',
    iosBundleId: 'com.example.notas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhWYN64lFCPF56Yl9I7I7CejAj4307ZhM',
    appId: '1:828623567114:ios:80f00557f23e1f5be6e2f3',
    messagingSenderId: '828623567114',
    projectId: 'notas-3c51d',
    storageBucket: 'notas-3c51d.appspot.com',
    iosClientId:
        '828623567114-5u1j71lmsun4c449riqvpq2of81g0c2s.apps.googleusercontent.com',
    iosBundleId: 'com.example.notas',
  );
}
